---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kiali-prometheus-override
  namespace: istio-system
data:
  config.yaml: |
    external_services:
      prometheus:
        url: http://prometheus.app:9090
    istio_namespace: istio-system
    server:
      web_root: /kiali